// new line
// new line
// new line
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;

public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form adminFrame
     */
    public AdminFrame(int userId) {

        initComponents();
        //   getContentPane().add(cardContainer);
 
        setExtendedState(MAXIMIZED_BOTH);
        
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            Rectangle screenBounds = ge.getMaximumWindowBounds(); // Screen size excluding taskbar

            // Print the width and height of the maximized state
            int width = screenBounds.width;
            int height = screenBounds.height;
            System.out.println("Maximized Width: " + width);
            System.out.println("Maximized Height: " + height);

        

        this.userId = userId;

        greetAdmin();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        greetingHeading = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        mainPanel = new javax.swing.JPanel();
        studentPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        studentSeparator = new javax.swing.JSeparator();
        studentHeader = new javax.swing.JLabel();
        searchLabelStudent = new javax.swing.JLabel();
        searchFieldStudent = new javax.swing.JTextField();
        addAccBtn2 = new javax.swing.JButton();
        accountPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        removeAccBtn = new javax.swing.JButton();
        deactBtn = new javax.swing.JButton();
        activateBtn = new javax.swing.JButton();
        searchFieldAccount = new javax.swing.JTextField();
        searchLabelAccount = new javax.swing.JLabel();
        addAccBtn = new javax.swing.JButton();
        updateAccBtn = new javax.swing.JButton();
        accmanagementBtn = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(900, 428));

        greetingHeading.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        greetingHeading.setText("WELCOME");
        greetingHeading.setPreferredSize(new java.awt.Dimension(741, 428));

        mainPanel.setLayout(new java.awt.CardLayout());

        studentPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        studentPanel.setPreferredSize(new java.awt.Dimension(902, 600));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Last Name", "First Name", "Middle Name", "Address"
            }
        ));
        jTable2.setPreferredSize(new java.awt.Dimension(1194, 402));
        jScrollPane2.setViewportView(jTable2);

        studentHeader.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        studentHeader.setText("STUDENT MANAGEMENT");

        searchLabelStudent.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        searchLabelStudent.setText("SEARCH:");

        searchFieldStudent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        searchFieldStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldStudentActionPerformed(evt);
            }
        });

        addAccBtn2.setText("ADD ACCOUNT");

        javax.swing.GroupLayout studentPanelLayout = new javax.swing.GroupLayout(studentPanel);
        studentPanel.setLayout(studentPanelLayout);
        studentPanelLayout.setHorizontalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(studentPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(searchLabelStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchFieldStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(studentPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(studentHeader))
                    .addGroup(studentPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addAccBtn2)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        studentPanelLayout.setVerticalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(studentHeader)
                .addGap(18, 18, 18)
                .addComponent(studentSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchFieldStudent)
                    .addComponent(searchLabelStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGroup(studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(studentPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(addAccBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        mainPanel.add(studentPanel, "studentPanel");

        accountPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "ACCOUNT MANAGEMENT", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N
        accountPanel.setPreferredSize(new java.awt.Dimension(1470, 500));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "FIRST NAME", "MIDDLE NAME", "LAST  NAME", "EMAIL", "CONTACT NUMBER", "USERNAME", "PASSWORD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        removeAccBtn.setText("REMOVE ACCOUNT");

        deactBtn.setText("DEACTIVATE ACCOUNT");
        deactBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deactBtnActionPerformed(evt);
            }
        });

        activateBtn.setText("ACTIVATE ACCOUNT");
        activateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activateBtnActionPerformed(evt);
            }
        });

        searchFieldAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        searchFieldAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldAccountActionPerformed(evt);
            }
        });

        searchLabelAccount.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        searchLabelAccount.setText("SEARCH:");

        addAccBtn.setText("ADD ACCOUNT");
        addAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAccBtnActionPerformed(evt);
            }
        });

        updateAccBtn.setText("UPDATE ACCOUNT");
        updateAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAccBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountPanelLayout = new javax.swing.GroupLayout(accountPanel);
        accountPanel.setLayout(accountPanelLayout);
        accountPanelLayout.setHorizontalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(accountPanelLayout.createSequentialGroup()
                        .addComponent(searchLabelAccount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchFieldAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 942, Short.MAX_VALUE))
                    .addGroup(accountPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deactBtn)
                            .addComponent(removeAccBtn)
                            .addComponent(activateBtn)
                            .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(updateAccBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addAccBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))
                        .addGap(37, 37, 37))))
        );
        accountPanelLayout.setVerticalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLabelAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(searchFieldAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountPanelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(addAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(removeAccBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(activateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deactBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(accountPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );

        mainPanel.add(accountPanel, "accountPanel");

        accmanagementBtn.setText("ACCOUNT MANAGEMENT");
        accmanagementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accmanagementBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(greetingHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(accmanagementBtn)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(greetingHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(accmanagementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void activateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activateBtnActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        
        card.show(mainPanel, "student");
    }//GEN-LAST:event_activateBtnActionPerformed

    private void addAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addAccBtnActionPerformed

    private void searchFieldAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldAccountActionPerformed

    private void searchFieldStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldStudentActionPerformed

    private void accmanagementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accmanagementBtnActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        
        card.show(mainPanel, "accountPanel");
    }//GEN-LAST:event_accmanagementBtnActionPerformed

    private void deactBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deactBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deactBtnActionPerformed

    private void updateAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAccBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateAccBtnActionPerformed

    public void greetAdmin() {

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/students", "root", "Gwapsako@2004");
            String query = "SELECT * FROM userinformation WHERE userId = ?";
            PreparedStatement ps = con.prepareStatement(query);

            ps.setInt(1, userId);

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String user = rs.getString("userType");
                greetingHeading.setText(greetingHeading.getText() + ", " + user);

            }

        } catch (Exception e) {

        }
    }

    public static void main(String args[]) {
        new AdminFrame(userId).setVisible(true);
    }
    static int userId;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accmanagementBtn;
    private javax.swing.JPanel accountPanel;
    private javax.swing.JButton activateBtn;
    private javax.swing.JButton addAccBtn;
    private javax.swing.JButton addAccBtn2;
    private javax.swing.JButton deactBtn;
    public static javax.swing.JLabel greetingHeading;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton removeAccBtn;
    private javax.swing.JTextField searchFieldAccount;
    private javax.swing.JTextField searchFieldStudent;
    private javax.swing.JLabel searchLabelAccount;
    private javax.swing.JLabel searchLabelStudent;
    private javax.swing.JLabel studentHeader;
    private javax.swing.JPanel studentPanel;
    private javax.swing.JSeparator studentSeparator;
    private javax.swing.JButton updateAccBtn;
    // End of variables declaration//GEN-END:variables
}
